import pyvisa

rm= pyvisa.ResourceManager()
print(rm.list_resources())
daq = rm.open_resource('ASRL10::INSTR')
daq.write("*CLS")
daq.write("*RST")
test_w_1 = float(daq.query("MEAS:RES? (@101)"))
test_w_2 = float(daq.query("MEAS:RES? (@102)"))
test_w_3 = float(daq.query("MEAS:RES? (@103)"))
test_w_4 = float(daq.query("MEAS:RES? (@104)"))
test_w_5 = float(daq.query("MEAS:RES? (@105)"))
test_w_6 = float(daq.query("MEAS:RES? (@106)"))
test_w_7 = float(daq.query("MEAS:RES? (@107)"))
test_w_8 = float(daq.query("MEAS:RES? (@108)"))
test_w_9 = float(daq.query("MEAS:RES? (@109)"))
test_w_10 = float(daq.query("MEAS:RES? (@110)"))
test_w_11 = float(daq.query("MEAS:RES? (@111)"))
test_w_12 = float(daq.query("MEAS:RES? (@112)"))
test_w_13 = float(daq.query("MEAS:RES? (@113)"))
test_w_14 = float(daq.query("MEAS:RES? (@114)"))
test_w_15 = float(daq.query("MEAS:RES? (@115)"))
test_w_16 = float(daq.query("MEAS:RES? (@116)"))
print(daq.query("SYST:ERR?"))
daq.close()
rm.close()

print(test_w_1)
print(test_w_2)
print(test_w_3)
print(test_w_4)
print(test_w_5)
print(test_w_6)
print(test_w_7)
print(test_w_8)
print(test_w_9)
print(test_w_10)
print(test_w_11)
print(test_w_12)
print(test_w_13)
print(test_w_14)
print(test_w_15)
print(test_w_16)